export default [
  {
    languageOptions: {
      globals: {
        paths: {
          root: __dirname,
          vpcs: `${__dirname}/.vpcs`,
          apps: `${__dirname}/apps`,
          ...globals.node, // Add node globals if defined
        },
      },
      files: ['**/*.js', '**/*.mjs'],
      parserOptions: {
        sourceType: 'module',
      },
      rules: {
        'array-callback-return': { allowImplicit: true, allowVoid: false, checkForEach: true },
        'constructor-super': 'warn',
        'for-direction': 'error',
        'getter-return': 'error',
        'no-alert': 'error',
        'no-async-promise-executor': 'warn',
        'no-await-in-loop': 'warn',
        'no-class-assign': 'off',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'warn',
        'no-const-assign': 'error',
        'no-const-binary-expression': 'error',
        'no-constant-condition': {
          checkLoopsIfElse: true,
          checkLoopsWhile: true,
          checkSwitch: true,
          checkTry: false,
          checkLoopsFor: true,
        },
        'no-constructor-return': 'error',
        'no-console': 'off',
        'no-continue': 'warn',
        'no-control-regex': 'warn',
        'no-debugger': 'warn',
        'no-delete-var': 'warn',
        'no-dupe-args': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'error',
        'no-else-return': 'warn',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-function': 'error',
        'no-empty-pattern': [
          'error',
          {
            allowEmptyCatch: true,
            allowEmptyFor: true,
            allowEmptyIf: true,
            allowEmptyWhile: true,
            allowObjectPatternsAsParameters: true,
          },
        ],
        'no-eq-null': 'error',
        'no-eval': 'error',
        'no-ex-assign': 'error',
        'no-extend-native': false,
        'no-fallthrough': 'warn',
        'no-func-reassign': 'warn',
        'no-import-assign': 'error',
        'no-inner-declarations': 'warn',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'warn',
        'no-loss-of-precision': 'warn',
        'no-misleading-character-class': 'off',
        'no-new-native-nonconstructor': 'warn',
        'no-obj-calls': 'off',
        'no-octal': 'off',
        'no-promise-executor-return': 'error',
        'no-proto': 'off',
        'no-prototype-builtins': 'off',
        'no-redeclare': 'off',
        'no-regex-spaces': 'warn',
        'no-return-assign': 'warn',
        'no-return-await': 'warn',
        'no-self-assign': 'error',
        'no-self-compare': 'warn',
        'no-setter-return': 'warn',
        'no-shadow': 'warn',
        'no-sparse-arrays': 'off',
        'no-template-curly-in-string': 'warn',
        'no-this-before-super': 'warn',
        'no-throw-literal': 'warn',
        'no-undef': 'warn',
        'no-unreachable': 'warn',
        'no-unreachable-loop': 'warn',
        'no-unsafe-finally': 'warn',
        'no-unsafe-negation': 'warn',
        'no-unsafe-optional-chaining': 'warn',
        'no-unused-labels': 'warn',
        'no-unused-vars': 'error',
        'no-useless-backreference': 'error',
        'no-useless-catch': 'warn',
        'no-useless-computed-key': 'warn',
        'no-unexpected-multiline': 'warn',
        'no-unexpected-multiline-in-expression': 'warn',
        'no-unmodified-loop-condition': 'warn',
        'no-unreachable-loop': 'warn',
        'no-unreachable-loop-in-break': 'warn',
        'no-unreachable-loop-in-continue': 'warn',
        'no-unsafe-optional-chaining': 'warn',
        'no-unsafe-return': 'warn',
        'no-unsafe-optional-chaining': 'warn',
        'no-unused-expressions': 'warn',
        'no-unused-labels': 'warn',
        'no-unused-vars': 'warn',
        'no-use-before-define': 'warn',
        'no-useless-call': 'warn',
        'no-useless-catch': 'warn',
        'no-var': 'error',
        'prefer-const': 'warn',
        'prefer-destructuring': 'off',
        'prefer-template': 'off',
        semi: 'never',
        'use-isnan': 'warn',
        'valid-typeof': 'warn',
        'wrap-iife': 'off',
      },
      ecmaVersion: 2021,
    },
  },
];
