---
# Environment Information
cloudProvider: gcp
deployEnv: production
region: us-central1
vpc: prod


# namespace: groupon-admin-production


# Scaling
minReplicas: 2
maxReplicas: 4

envVars:
  NEXT_PUBLIC_ENV: production
  JTIER_RUN_CONFIG: '.meta/deployment/cloud/secrets/cloud/production-us-central1.yml'
  LOG_TO_STDOUT: 'true'


# If you need to configure the size of your application specifically in different environments,
# you can override the common and default values here
#
# Resource Requests
# cpus:
#   main:
#     request: 1000m
# memory:
#   main:
#     request: 500Mi
#     limit: 500Mi
