secretStrings:
  rbac-ui:
    NEXT_PRIVATE_RBAC_CLIEND_ID: "xxx"
    NEXT_PRIVATE_RBAC_API_URL: "http://rbac.production.service"
    NEXT_PRIVATE_USERS_NA_API_KEY: "b1ab3da034b8874a-rbac-ui"
    NEXT_PRIVATE_USERS_NA_REGION: "us-central1"
    NEXT_PRIVATE_USERS_EMEA_API_KEY: "xxx"
    NEXT_PRIVATE_USERS_EMEA_REGION: "eu-west-1"
    NEXT_PRIVATE_USERS_API_URL: "http://users-service.production.service/users/v1"
    NEXT_PRIVATE_JWT_SECRET: "XXX"
