secretStrings:
  rbac-ui:
    NEXT_PRIVATE_RBAC_CLIEND_ID: "91e489c2caa8471d8550c7f7908ad94a_rbacui"
    NEXT_PRIVATE_RBAC_API_URL: "http://rbac.production.service"
    NEXT_PRIVATE_USERS_NA_API_KEY: "b1ab3da034b8874a-rbac-ui"
    NEXT_PRIVATE_USERS_NA_REGION: "us-central1"
    NEXT_PRIVATE_USERS_EMEA_API_KEY: "4bc3d510c12e5adb-rbac-ui"
    NEXT_PRIVATE_USERS_EMEA_REGION: "eu-west-1"
    NEXT_PRIVATE_USERS_API_URL: "http://users-service.production.service/users/v1"
    NEXT_PRIVATE_JWT_SECRET: "asDhvG4g15UvssdFTYg1f651f5f-feYInbffd479a4as51das35d1as35d1as35d1as35d130dfg5df9"
