

export class AsanaIssueContent {


    get week_text(): string {
        return this._week_text;
    }

    get vp_text(): string {
        return this._vp_text;
    }

    get project_text(): string {
        return this._project_text;
    }

    get issues_owners_text(): string {
        return this._issues_owners_text;
    }

    get kindly_reminder_close_message(): string {
        return this._kindly_reminder_close_message;
    }

    // ---

    private _week_text: string =
        "<body>"
        + "⚠️ <strong>This ticket has been automatically generated.</strong>"
        + " " + "For any inquiries, don't hesitate to get in touch with the responsible manager, <a href=\"https://app.asana.com/0/profile/1204853356727858\" data-asana-gid=\"1204851503350993\" data-asana-accessible=\"true\" data-asana-type=\"user\" data-asana-dynamic=\"true\">@Tomas Zaruba</a>."
        + "\n"
        + "\n"
        + "<strong>Big Picture</strong> is an initiative by the Transformation Team aimed at ensuring JIRA operates in a transparent, clean, data-minable, and efficient manner. To align with these objectives, this ticket has been assigned to you. A comprehensive set of rules and requirements, delineated within the KPI policy, has been established for all Engineering and Product Management teams."
        + " " + "You can access the detailed guidelines through the following link: <a href=\"https://docs.google.com/presentation/d/16fS5RNw7bCRHuOqSy3EB96E7jpiGiSO-r8DP4J8MdJU/edit#slide=id.g2e11009b967_0_0\">KPI Policy Presentation</a>."
        + "\n"
        + "\n"
        + "Just as a reminder, we prepared the handbook: <a href=\"https://docs.google.com/presentation/d/1b7MCQILYj6f9WaIzgdidRebbm7gFWcfQ/edit#slide=id.p1\">Big Picture JIRA Standardization</a>"
        + "\n"
        + 'Support Google Chat can be found here: <a href=\"https://chat.google.com/room/AAAAgC0AsCk?cls=4">Big Picture Chat</a>.'
        + "\n"
        + "As a responsible manager, it is imperative to ensure the resolution of each issue by the time the next report is generated. Reports are produced weekly on Mondays."
        + " " + "Additional information is available on the introductory page, including a detailed description, in the &quot;Kindly Reminder&quot; worksheet, which can be accessed here: " +
        "<a href=\"https://docs.google.com/spreadsheets/d/1sc1odN1DK72fYZVVlMz99o18mKFWKKfUeLLUSll5Twk/edit?gid=303737385#gid=303737385\">Kindly Reminder Worksheet</a>."
        + "\n"
        + "\n"
        + "\n"
        + 'Active Week Issue Log: <a href="{worksheet_link}">Week {week_number}</a>'
        + "\n"
        + "\n"
        + "\n"
        + "<hr />"
        + "For any technical questions or ideas for improving the generation mechanism (because the number of issues will increase with the number of applied rules),"
        + " please contact <a href=\"https://app.asana.com/0/profile/1204853356727858\" data-asana-gid=\"1204851503350993\" data-asana-accessible=\"true\" data-asana-type=\"user\" data-asana-dynamic=\"true\">@Tomas Zaruba</a>"
        + " as soon as possible, so that new rules or improved automation can be applied."
        + "</body>"


    private _vp_text: string =
        "<body>" +
        '⚠️ <strong>This ticket has been automatically generated by Kindly Reminder</strong>'
        + "\n"
        + 'For more information, read the parent ticket'
        + ' <a href="https://app.asana.com/0/{project_id}/{week_ticket_id}/f" data-asana-gid="{week_ticket_id}" data-asana-accessible="true" data-asana-type="task" data-asana-project="{project_id}" data-asana-dynamic="true">Week {week_number} -  General Report</a>.'
        + "\n"
        + "\n"
        + "<strong>Big Picture - Weekly Report</strong>"
        + "\n"
        + "<ul>"
        + "<li><strong>Week:</strong> {week_number}</li>"
        +  "<li><strong>Date Created:</strong> {created_as_string}</li>"
        + "<li><strong>Deadline:</strong> {deadline_as_string}</li>"
        + "<li><strong>Number of Reported Issues:</strong> {number_of_issues}</li>"
        + "</ul>"
        + "\n"
        + "\n"
        + "<h1>Issues:</h1>"
        + "\n"
        + "{list_of_issues}"
        + "\n"
        + "Please note that the format of this report, including the list of active issues, may be subject to change throughout the quarter."
        + "\n"
        + 'You can find all issues here: <a href="{worksheet_link}">Week {week_number}</a>'
        + "\n"
        + "\n"
        + "</body>"

    private _project_text: string =
        "<body>" +
        '⚠️ <strong>This ticket has been automatically generated by Kindly Reminder</strong>'
        + "\n"
        + 'For more information, read the parent ticket'
        + ' <a href="https://app.asana.com/0/{project_id}/{week_ticket_id}/f" data-asana-gid="{week_ticket_id}" data-asana-accessible="true" data-asana-type="task" data-asana-project="{project_id}" data-asana-dynamic="true">Week {week_number} -  General Report</a>.'
        + "\n"
        + "\n"
        + "<strong>Big Picture - Weekly Report for Project {project_name}</strong>"
        + "\n"
        + "<ul>"
        + "<li><strong>Week:</strong> {week_number}</li>"
        +  "<li><strong>Date Created:</strong> {created_as_string}</li>"
        + "<li><strong>Deadline:</strong> {deadline_as_string}</li>"
        + "<li><strong>Number of Reported Issues:</strong> {number_of_issues}</li>"
        + "</ul>"
        + "\n"
        + "\n"
        + "<h1>Issues:</h1>"
        + "\n"
        + "{list_of_issues}"
        + "\n"
        + "Please note that the format of this report, including the list of active issues, may be subject to change throughout the quarter."
        + "\n"
        + 'You can find all issues here: <a href="{worksheet_link}">Week {week_number}</a>'
        + "\n"
        + "\n"
        + "</body>"


    private _issues_owners_text: string =
        "<body>" +
        '⚠️ <strong>This ticket has been automatically generated by Kindly Reminder</strong>'
        + "\n"
        + 'For more information, read the parent ticket'
        + ' <a href="https://app.asana.com/0/{project_id}/{week_ticket_id}/f" data-asana-gid="{week_ticket_id}" data-asana-accessible="true" data-asana-type="task" data-asana-project="{project_id}" data-asana-dynamic="true">Week {week_number} -  General Report</a>.'
        + "\n"
        + "\n"
        + "<strong>Big Picture - Weekly Report for Issue owners</strong>"
        + "\n"
        + "<ul>"
        + "<li><strong>Week:</strong> {week_number}</li>"
        + "<li><strong>Date Created:</strong> {created_as_string}</li>"
        + "<li><strong>Deadline:</strong> {deadline_as_string}</li>"
        + "<li><strong>Number of Reported Issues:</strong> {number_of_issues}</li>"
        + "</ul>"
        + "\n"
        + "\n"
        + "Please note that the format of this report, including the list of active issues, may be subject to change throughout the quarter."
        + "\n"
        + "<h1>Issues:</h1>"
        + "\n"
        + "{list_of_issues}"
        + "\n"
        + 'You can find all issues here: <a href="{worksheet_link}">Week {week_number}</a>'
        + "\n"
        + "\n"
        + "</body>"


    private _kindly_reminder_close_message: string =
        "<body>"
        + "⚠️ <strong>This ticket has been automatically closed due to expiration..</strong>"
        + "\n"
        + "\n"
        + "We hope that all the requests sent to you by Kindly Reminder have been addressed. "
        + "Please note that this is an automated message and does not account for whether the issue was resolved, left unresolved, or if the ticket was simply forgotten."
        + "\n"
        + "\n"
        + "If the necessary fixes were not completed on time, you may receive a RedFlag."
        + "\n"
        + "\n"
        + "Should you disagree with any penalties, you can report your concern by submitting a form following the same process outlined in this ticket: " +
        "<a href=\"https://app.asana.com/0/1207778959375434/1207885845852637/f\" data-asana-gid=\"1207885845852637\" data-asana-accessible=\"true\" data-asana-type=\"task\" data-asana-project=\"1207778959375434\" data-asana-dynamic=\"true\">Week {week_number} -  General Report</a> "
        + "</body>"



}
